-- Revise the initial Credit Card Match schema for Supabase Auth, extensible
-- filters, saved survey data, and owner-scoped row-level security.
--
-- This migration is intentionally additive to migration history. It migrates
-- an existing public.users row only when its email maps to exactly one
-- auth.users row; otherwise it stops before discarding legacy user data.

BEGIN;

-- Supabase Auth owns identity and email. Application-specific names live here.
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    -- TODO(TBD): Decide whether first_name and last_name are required at sign-up.
    first_name VARCHAR(50),
    last_name VARCHAR(50)
);

-- Guard the one-time transition from the initial bigint user identifiers.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM public.users AS legacy_user
        LEFT JOIN auth.users AS auth_user
            ON LOWER(auth_user.email) = LOWER(legacy_user.email)
        GROUP BY legacy_user.user_id
        HAVING COUNT(auth_user.id) <> 1
    ) THEN
        RAISE EXCEPTION
            'Each public.users row must match exactly one auth.users email before this migration can run';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM public.users AS legacy_user
        JOIN auth.users AS auth_user
            ON LOWER(auth_user.email) = LOWER(legacy_user.email)
        GROUP BY auth_user.id
        HAVING COUNT(legacy_user.user_id) > 1
    ) THEN
        RAISE EXCEPTION
            'Multiple public.users rows map to the same auth.users row';
    END IF;
END;
$$;

INSERT INTO public.profiles (id, first_name, last_name)
SELECT auth_user.id, legacy_user.first_name, legacy_user.last_name
FROM public.users AS legacy_user
JOIN auth.users AS auth_user
    ON LOWER(auth_user.email) = LOWER(legacy_user.email);

ALTER TABLE public.user_preferences
    ADD COLUMN auth_user_id UUID;

ALTER TABLE public.recommendations
    ADD COLUMN auth_user_id UUID;

UPDATE public.user_preferences AS preference
SET auth_user_id = auth_user.id
FROM public.users AS legacy_user
JOIN auth.users AS auth_user
    ON LOWER(auth_user.email) = LOWER(legacy_user.email)
WHERE preference.user_id = legacy_user.user_id;

UPDATE public.recommendations AS recommendation
SET auth_user_id = auth_user.id
FROM public.users AS legacy_user
JOIN auth.users AS auth_user
    ON LOWER(auth_user.email) = LOWER(legacy_user.email)
WHERE recommendation.user_id = legacy_user.user_id;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM public.user_preferences
        WHERE auth_user_id IS NULL
    ) OR EXISTS (
        SELECT 1
        FROM public.recommendations
        WHERE auth_user_id IS NULL
    ) THEN
        RAISE EXCEPTION
            'All legacy user-owned rows must map to Supabase Auth before this migration can run';
    END IF;
END;
$$;

ALTER TABLE public.user_preferences
    ALTER COLUMN auth_user_id SET NOT NULL;
ALTER TABLE public.user_preferences
    DROP COLUMN user_id;
ALTER TABLE public.user_preferences
    RENAME COLUMN auth_user_id TO user_id;

ALTER TABLE public.user_preferences
    ADD CONSTRAINT user_preferences_user_id_key UNIQUE (user_id),
    ADD CONSTRAINT user_preferences_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

ALTER TABLE public.recommendations
    ALTER COLUMN auth_user_id SET NOT NULL;
ALTER TABLE public.recommendations
    DROP COLUMN user_id;
ALTER TABLE public.recommendations
    RENAME COLUMN auth_user_id TO user_id;

ALTER TABLE public.recommendations
    ADD CONSTRAINT recommendations_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

COMMENT ON TABLE public.recommendations IS
    'Reserved for future saved recommendations; unused in the MVP.';

DROP TABLE public.users;

-- URL-facing filter vocabulary. Filters are rows so the vocabulary can grow
-- without adding columns or changing application query shapes.
CREATE TABLE public.filters (
    filter_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    label TEXT NOT NULL,
    description TEXT
);

CREATE TABLE public.card_filters (
    card_id BIGINT NOT NULL REFERENCES public.credit_cards(card_id) ON DELETE CASCADE,
    filter_id BIGINT NOT NULL REFERENCES public.filters(filter_id) ON DELETE CASCADE,
    PRIMARY KEY (card_id, filter_id)
);

INSERT INTO public.filters (slug, label, description)
VALUES
    ('popular-cards', 'Popular Cards', NULL),
    ('cashback', 'Cashback', NULL),
    ('new-to-credit', 'New-to-Credit', NULL);

ALTER TABLE public.credit_cards
    ADD COLUMN image_url TEXT,
    ADD COLUMN description TEXT,
    -- TODO(TBD): Confirm allowed reward_type values; candidates are cashback, points, and miles.
    ADD COLUMN reward_type TEXT,
    -- TODO(TBD): Define the allowed credit_level_required values.
    ADD COLUMN credit_level_required TEXT,
    ADD COLUMN source_url TEXT,
    ADD COLUMN last_verified_at TIMESTAMPTZ,
    ADD COLUMN is_verified BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE public.card_benefits (
    card_benefit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id BIGINT NOT NULL REFERENCES public.credit_cards(card_id) ON DELETE CASCADE,
    description TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0
);

ALTER TABLE public.card_rewards
    ADD CONSTRAINT card_rewards_card_id_category_id_key
        UNIQUE (card_id, category_id);

ALTER TABLE public.user_preferences
    -- TODO(TBD): Define the allowed income_range values.
    ADD COLUMN income_range TEXT;

-- TODO(TBD): Confirm the credit_score_range value for no credit history;
-- `no_history` is the current candidate.
-- TODO(TBD): Decide whether user_preferences.monthly_spend overlaps with the
-- category-level amounts in user_category_spend.
-- TODO(TBD): Decide whether accepts_annual_fee and wants_travel_rewards remain
-- after user_filter_preferences becomes the general preference mechanism.

CREATE TABLE public.user_category_spend (
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    category_id BIGINT NOT NULL REFERENCES public.reward_categories(category_id) ON DELETE CASCADE,
    monthly_amount DECIMAL(10,2) NOT NULL CHECK (monthly_amount >= 0),
    UNIQUE (user_id, category_id)
);

CREATE TABLE public.user_filter_preferences (
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    filter_id BIGINT NOT NULL REFERENCES public.filters(filter_id) ON DELETE CASCADE,
    preference TEXT NOT NULL CHECK (preference IN ('want', 'avoid')),
    UNIQUE (user_id, filter_id)
);

-- Foreign-key indexes. Primary-key and UNIQUE indexes already cover
-- profiles.id, user_preferences.user_id, card_rewards.card_id,
-- card_filters.card_id, user_category_spend.user_id, and
-- user_filter_preferences.user_id as leading columns.
CREATE INDEX card_rewards_category_id_idx
    ON public.card_rewards (category_id);
CREATE INDEX recommendations_user_id_idx
    ON public.recommendations (user_id);
CREATE INDEX recommendations_card_id_idx
    ON public.recommendations (card_id);
CREATE INDEX card_filters_filter_id_idx
    ON public.card_filters (filter_id);
CREATE INDEX card_benefits_card_id_idx
    ON public.card_benefits (card_id);
CREATE INDEX user_category_spend_category_id_idx
    ON public.user_category_spend (category_id);
CREATE INDEX user_filter_preferences_filter_id_idx
    ON public.user_filter_preferences (filter_id);

-- Every public table is protected by row-level security.
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.credit_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reward_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.card_rewards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.card_benefits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.filters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.card_filters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_category_spend ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_filter_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recommendations ENABLE ROW LEVEL SECURITY;

-- Catalog data is readable publicly. With no write policies, catalog writes
-- remain available only through trusted dashboard or service-role operations.
CREATE POLICY "Public can read credit cards"
    ON public.credit_cards FOR SELECT TO anon, authenticated
    USING (TRUE);
CREATE POLICY "Public can read reward categories"
    ON public.reward_categories FOR SELECT TO anon, authenticated
    USING (TRUE);
CREATE POLICY "Public can read card rewards"
    ON public.card_rewards FOR SELECT TO anon, authenticated
    USING (TRUE);
CREATE POLICY "Public can read card benefits"
    ON public.card_benefits FOR SELECT TO anon, authenticated
    USING (TRUE);
CREATE POLICY "Public can read filters"
    ON public.filters FOR SELECT TO anon, authenticated
    USING (TRUE);
CREATE POLICY "Public can read card filters"
    ON public.card_filters FOR SELECT TO anon, authenticated
    USING (TRUE);

REVOKE ALL
    ON TABLE public.credit_cards,
       public.reward_categories,
       public.card_rewards,
       public.card_benefits,
       public.filters,
       public.card_filters
    FROM anon, authenticated;
GRANT SELECT
    ON TABLE public.credit_cards,
       public.reward_categories,
       public.card_rewards,
       public.card_benefits,
       public.filters,
       public.card_filters
    TO anon, authenticated;

-- Profiles are owned by their auth.users identity.
CREATE POLICY "Owners can read profiles"
    ON public.profiles FOR SELECT TO authenticated
    USING ((SELECT auth.uid()) = id);
CREATE POLICY "Owners can create profiles"
    ON public.profiles FOR INSERT TO authenticated
    WITH CHECK ((SELECT auth.uid()) = id);
CREATE POLICY "Owners can update profiles"
    ON public.profiles FOR UPDATE TO authenticated
    USING ((SELECT auth.uid()) = id)
    WITH CHECK ((SELECT auth.uid()) = id);
CREATE POLICY "Owners can delete profiles"
    ON public.profiles FOR DELETE TO authenticated
    USING ((SELECT auth.uid()) = id);

-- Saved survey data and recommendations are visible and mutable only by the
-- authenticated owner identified by user_id.
CREATE POLICY "Owners can read user preferences"
    ON public.user_preferences FOR SELECT TO authenticated
    USING ((SELECT auth.uid()) = user_id);
CREATE POLICY "Owners can create user preferences"
    ON public.user_preferences FOR INSERT TO authenticated
    WITH CHECK ((SELECT auth.uid()) = user_id);
CREATE POLICY "Owners can update user preferences"
    ON public.user_preferences FOR UPDATE TO authenticated
    USING ((SELECT auth.uid()) = user_id)
    WITH CHECK ((SELECT auth.uid()) = user_id);
CREATE POLICY "Owners can delete user preferences"
    ON public.user_preferences FOR DELETE TO authenticated
    USING ((SELECT auth.uid()) = user_id);

CREATE POLICY "Owners can read category spend"
    ON public.user_category_spend FOR SELECT TO authenticated
    USING ((SELECT auth.uid()) = user_id);
CREATE POLICY "Owners can create category spend"
    ON public.user_category_spend FOR INSERT TO authenticated
    WITH CHECK ((SELECT auth.uid()) = user_id);
CREATE POLICY "Owners can update category spend"
    ON public.user_category_spend FOR UPDATE TO authenticated
    USING ((SELECT auth.uid()) = user_id)
    WITH CHECK ((SELECT auth.uid()) = user_id);
CREATE POLICY "Owners can delete category spend"
    ON public.user_category_spend FOR DELETE TO authenticated
    USING ((SELECT auth.uid()) = user_id);

CREATE POLICY "Owners can read filter preferences"
    ON public.user_filter_preferences FOR SELECT TO authenticated
    USING ((SELECT auth.uid()) = user_id);
CREATE POLICY "Owners can create filter preferences"
    ON public.user_filter_preferences FOR INSERT TO authenticated
    WITH CHECK ((SELECT auth.uid()) = user_id);
CREATE POLICY "Owners can update filter preferences"
    ON public.user_filter_preferences FOR UPDATE TO authenticated
    USING ((SELECT auth.uid()) = user_id)
    WITH CHECK ((SELECT auth.uid()) = user_id);
CREATE POLICY "Owners can delete filter preferences"
    ON public.user_filter_preferences FOR DELETE TO authenticated
    USING ((SELECT auth.uid()) = user_id);

CREATE POLICY "Owners can read recommendations"
    ON public.recommendations FOR SELECT TO authenticated
    USING ((SELECT auth.uid()) = user_id);
CREATE POLICY "Owners can create recommendations"
    ON public.recommendations FOR INSERT TO authenticated
    WITH CHECK ((SELECT auth.uid()) = user_id);
CREATE POLICY "Owners can update recommendations"
    ON public.recommendations FOR UPDATE TO authenticated
    USING ((SELECT auth.uid()) = user_id)
    WITH CHECK ((SELECT auth.uid()) = user_id);
CREATE POLICY "Owners can delete recommendations"
    ON public.recommendations FOR DELETE TO authenticated
    USING ((SELECT auth.uid()) = user_id);

REVOKE ALL
    ON TABLE public.profiles,
       public.user_preferences,
       public.user_category_spend,
       public.user_filter_preferences,
       public.recommendations
    FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE public.profiles,
       public.user_preferences,
       public.user_category_spend,
       public.user_filter_preferences,
       public.recommendations
    TO authenticated;
REVOKE ALL
    ON SEQUENCE public.credit_cards_card_id_seq,
                public.reward_categories_category_id_seq,
                public.card_rewards_card_reward_id_seq,
                public.card_benefits_card_benefit_id_seq,
                public.filters_filter_id_seq,
                public.user_preferences_preference_id_seq,
                public.recommendations_recommendation_id_seq
    FROM anon, authenticated;
GRANT USAGE, SELECT
    ON SEQUENCE public.user_preferences_preference_id_seq,
                public.recommendations_recommendation_id_seq
    TO authenticated;

-- The MVP application upserts a user's profile immediately before saving
-- survey answers.
-- OPTIONAL PROFILE-CREATION TRIGGER (not enabled by this migration)
-- TODO(TBD): Decide whether every auth.users insert should automatically create
-- a profile. If accepted, move the reviewed statements below into a later
-- migration and confirm the metadata keys used for first and last names.
--
-- CREATE FUNCTION public.handle_new_auth_user()
-- RETURNS TRIGGER
-- LANGUAGE plpgsql
-- SECURITY DEFINER SET search_path = ''
-- AS $$
-- BEGIN
--     INSERT INTO public.profiles (id, first_name, last_name)
--     VALUES (
--         NEW.id,
--         NEW.raw_user_meta_data ->> 'first_name',
--         NEW.raw_user_meta_data ->> 'last_name'
--     );
--     RETURN NEW;
-- END;
-- $$;
--
-- CREATE TRIGGER on_auth_user_created
--     AFTER INSERT ON auth.users
--     FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user();

COMMIT;
