-- Initial Credit Card Match schema.
-- Add reviewed CREATE TABLE(done), ALTER TABLE, index, row-level-security, and policy statements below.

--for those using the app
CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR (100) NOT NULL UNIQUE
);

--individual card information
CREATE TABLE credit_cards (
    card_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issuer VARCHAR(50) NOT NULL,
    card_name VARCHAR(100) NOT NULL,
    annual_fee DECIMAL(10,2) NOT NULL DEFAULT 0,
    intro_offer VARCHAR(255), 
    apply_url VARCHAR (255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

--categories of card rewards
CREATE TABLE reward_categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(50) NOT NULL UNIQUE
);

--the reward info for each card
CREATE TABLE card_rewards (
    card_reward_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    reward_rate DECIMAL(4,2) NOT NULL,
    FOREIGN KEY (card_id) REFERENCES credit_cards(card_id),
    FOREIGN KEY (category_id) REFERENCES reward_categories(category_id)
);

--user preferneces, set during the survey
CREATE TABLE user_preferences (
    preference_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    credit_score_range VARCHAR(30),
    monthly_spend DECIMAL(10,2),
    accepts_annual_fee BOOLEAN,
    wants_travel_rewards BOOLEAN,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

--saved recommendations for each user after the survey
CREATE TABLE recommendations (
    recommendation_id BIGINT GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    user_id BIGINT NOT NULL,
    card_id BIGINT NOT NULL,
    match_score DECIMAL(5,2) NOT NULL,
    explanation VARCHAR(500),
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (card_id) REFERENCES credit_cards(card_id)
);
